### ISSUE TITLE
Dumb Init and systemd?

### ISSUE THREAD

**Issue by KarstenVogt** [PasseiDireto/gh-runner#103]
Hi Mateus,

thank you so much for sharing this repo with the world. :)

Since I'm new to the sysbox world I'm wondering: why are you running Dumb Init when you have systemd in your baseimage? Are there benefits doing so?

Greetings to Brazil from Germany
Karsten

**Comment by mat-machado** [comment]
Hi Karsten!

Thank you for your comment!

We're using a dumb-init to avoid possible SIGTERM to the runner container, because when you have a process with PID 1, could be prioritazed and kill our process, so we init a dumb process to if something happens, our applicantion is not affected.

If you want more details, this project has a good documentation: https://github.com/Yelp/dumb-init

Best Regards,
Mateus Machado
